name: Update Battery Data Daily

on:
  schedule:
    # Run every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write
  pull-requests: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Debug - Check environment
      run: |
        echo "Current directory: $(pwd)"
        echo "Files in directory:"
        ls -la
        echo "API key is set: ${{ secrets.MASTR_API_KEY != '' }}"
        
    - name: Update battery data
      env:
        MASTR_API_KEY: ${{ secrets.MASTR_API_KEY }}
      run: |
        python collect_dashboard_data.py --min-power 5000 --min-capacity 5000
        
    - name: Debug - Check results
      run: |
        echo "Files after script execution:"
        ls -la *.json || echo "No JSON files found"
        echo "Git status:"
        git status
        
    - name: Configure Git
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        
    - name: Check for changes
      id: check_changes
      run: |
        # Check for new untracked JSON files
        if git ls-files --others --exclude-standard | grep -q "\.json$"; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected - new JSON files found"
          git ls-files --others --exclude-standard | grep "\.json$"
        elif ! git diff --quiet; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected - modified files found"
          git diff --name-only
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
        
    - name: Commit and push if changes
      if: steps.check_changes.outputs.changes == 'true'
      run: |
        git add *.json
        git commit -m "🤖 Auto-update battery data - $(date +'%Y-%m-%d')"
        echo "Attempting to push to repository..."
        git remote -v
        git push 